[project]
name = "real-life-situation"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.0",
    "opencv-python>=4.6.0.66",
    "requests>=2.28.1",
    "timesetter>=1.8",
]

[tool.pyright]
typeCheckingMode = "strict"
