[project]
name = "real_life_situation"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.24.0",
    "opencv-python>=4.6.0.66",
    "requests>=2.28.1",
    "timesetter>=1.7",
]
